name: dartd
description: CLI to analyze and remove unused Dart classes or modules.
version: 0.4.0
repository: https://github.com/Harineko0/dartd
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^6.4.1
  args: ^2.4.2
  path: ^1.9.0
  glob: ^2.1.2

executables:
  dartd: dartd

dev_dependencies:
  test: ^1.25.2
